'use strict';

const { sendEmail } = require('./mailer');

const CLINICAL_EMAIL = process.env.DEFAULT_CLINICAL_PARTNER_EMAIL || 'nanakwamedickson62@gmail.com';
const CLINICAL_HOTLINE = process.env.DEFAULT_CLINICAL_HOTLINE || '0551022714';
const NOTIFICATION_RECIPIENT = process.env.DEFAULT_NOTIFICATION_RECIPIENT || 'nanakwamedickson62@gmail.com';

/**
 * Sends email using Nodemailer (Gmail SMTP).
 * @param {object} options
 * @param {string|string[]} options.to - Recipient email or array of emails
 * @param {string} options.subject - Email subject line
 * @param {string} options.html - Email HTML content
 * @param {string} [options.from] - Sender address
 */
async function sendMail({ to, subject, html, from }) {
  return sendEmail({ to, subject, html, from });
}

/**
 * Sends a structured clinical referral dispatch email.
 * @param {object} opts
 * @param {string} opts.referenceCode - Anonymized reference code (e.g. REF-A3X9K2)
 * @param {string} [opts.department] - Department tag (anonymized)
 * @param {string} [opts.notes] - Intake notes from employee
 * @param {string} [opts.preferredTime] - Preferred contact time
 * @param {string} [opts.to] - Override recipient (defaults to clinical partner)
 */
async function sendClinicalDispatch({ referenceCode, department, notes, preferredTime, to }) {
  const recipient = to || CLINICAL_EMAIL;
  const timestamp = new Date().toISOString();

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f0f1a; color: #e0e0e0; border-radius: 12px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #6366f1, #8b5cf6); padding: 24px 32px;">
        <h1 style="margin: 0; color: #fff; font-size: 20px;">🏥 Confidential Clinical Referral</h1>
        <p style="margin: 4px 0 0; color: rgba(255,255,255,0.8); font-size: 13px;">Havilah Occupational Health Compliance System</p>
      </div>
      <div style="padding: 24px 32px;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; color: #9ca3af; width: 140px;">Reference Code</td><td style="padding: 8px 0; font-weight: 600; color: #a78bfa;">${referenceCode}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Department</td><td style="padding: 8px 0;">${department || 'Not specified'}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Preferred Time</td><td style="padding: 8px 0;">${preferredTime || 'Not specified'}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Timestamp</td><td style="padding: 8px 0;">${timestamp}</td></tr>
        </table>
        ${notes ? `<div style="margin-top: 16px; padding: 16px; background: rgba(255,255,255,0.05); border-radius: 8px; border-left: 3px solid #8b5cf6;"><p style="margin: 0 0 4px; color: #9ca3af; font-size: 12px;">INTAKE NOTES</p><p style="margin: 0; line-height: 1.6;">${notes}</p></div>` : ''}
        <div style="margin-top: 24px; padding: 12px 16px; background: rgba(99,102,241,0.1); border-radius: 8px; font-size: 12px; color: #9ca3af;">
          <strong>Privacy Notice:</strong> This is an automated, isolated request. No psychosocial data or hazard survey history is attached to protect employee privacy.
        </div>
      </div>
      <div style="padding: 16px 32px; background: rgba(255,255,255,0.03); font-size: 11px; color: #6b7280; text-align: center;">
        Clinical Hotline: ${CLINICAL_HOTLINE} &bull; Generated by Havilah Compliance Engine
      </div>
    </div>
  `;

  return sendMail({
    to: recipient,
    subject: `🏥 Clinical Referral ${referenceCode} - Confidential Intake`,
    html
  });
}

/**
 * Sends a high-risk intervention alert email (no PII).
 * @param {object} opts
 * @param {string} opts.surveyType - Survey instrument (e.g. 'phq9', 'copsoq3')
 * @param {string} opts.severityBand - Risk level (e.g. 'severe', 'critical')
 * @param {string} [opts.department] - Anonymized department tag
 * @param {string} [opts.to] - Override recipient
 */
async function sendInterventionAlert({ surveyType, severityBand, department, to }) {
  const recipient = to || CLINICAL_EMAIL;
  const timestamp = new Date().toISOString();

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f0f1a; color: #e0e0e0; border-radius: 12px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #ef4444, #dc2626); padding: 24px 32px;">
        <h1 style="margin: 0; color: #fff; font-size: 20px;">⚠️ High-Risk Intervention Alert</h1>
        <p style="margin: 4px 0 0; color: rgba(255,255,255,0.8); font-size: 13px;">Automated Hazard Detection - Immediate Review Required</p>
      </div>
      <div style="padding: 24px 32px;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; color: #9ca3af; width: 140px;">Survey Type</td><td style="padding: 8px 0; font-weight: 600;">${(surveyType || '').toUpperCase()}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Severity Band</td><td style="padding: 8px 0; color: #ef4444; font-weight: 600;">${(severityBand || '').toUpperCase()}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Department</td><td style="padding: 8px 0;">${department || 'Anonymized'}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Detected At</td><td style="padding: 8px 0;">${timestamp}</td></tr>
        </table>
        <div style="margin-top: 24px; padding: 12px 16px; background: rgba(239,68,68,0.1); border-radius: 8px; font-size: 12px; color: #fca5a5;">
          <strong>⚠️ Action Required:</strong> An anonymous assessment submission has triggered a high-severity alert. Please review departmental risk indicators and consider initiating a targeted intervention protocol.
        </div>
        <div style="margin-top: 12px; padding: 12px 16px; background: rgba(99,102,241,0.1); border-radius: 8px; font-size: 12px; color: #9ca3af;">
          <strong>Privacy Notice:</strong> No personally identifiable information is included. This alert contains only aggregate risk indicators.
        </div>
      </div>
      <div style="padding: 16px 32px; background: rgba(255,255,255,0.03); font-size: 11px; color: #6b7280; text-align: center;">
        Clinical Hotline: ${CLINICAL_HOTLINE} &bull; Generated by Havilah Compliance Engine
      </div>
    </div>
  `;

  return sendMail({
    to: recipient,
    subject: `⚠️ HIGH-RISK ALERT - ${(surveyType || '').toUpperCase()} Severity: ${(severityBand || '').toUpperCase()}`,
    html
  });
}

/**
 * Sends an anonymized whistleblower hazard escalation alert.
 * @param {object} opts
 * @param {string} opts.reportId - Anonymous report reference ID
 * @param {string} opts.category - Hazard category
 * @param {string} opts.urgency - Urgency level
 * @param {string} [opts.companyName] - Company name for context
 * @param {string} [opts.to] - Override recipient
 */
async function sendWhistleblowerAlert({ reportId, category, urgency, companyName, to }) {
  const recipient = to || CLINICAL_EMAIL;
  const timestamp = new Date().toISOString();

  const urgencyColors = {
    critical: '#ef4444',
    urgent: '#f59e0b',
    standard: '#6366f1'
  };
  const color = urgencyColors[urgency] || urgencyColors.standard;

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f0f1a; color: #e0e0e0; border-radius: 12px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, ${color}, ${color}dd); padding: 24px 32px;">
        <h1 style="margin: 0; color: #fff; font-size: 20px;">🛡️ Anonymous Hazard Escalation Report</h1>
        <p style="margin: 4px 0 0; color: rgba(255,255,255,0.8); font-size: 13px;">Whistleblower Protection - Confidential</p>
      </div>
      <div style="padding: 24px 32px;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; color: #9ca3af; width: 140px;">Report ID</td><td style="padding: 8px 0; font-weight: 600; color: #a78bfa;">${reportId}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Category</td><td style="padding: 8px 0; text-transform: capitalize;">${(category || '').replace(/_/g, ' ')}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Urgency</td><td style="padding: 8px 0; color: ${color}; font-weight: 600; text-transform: uppercase;">${urgency}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Organization</td><td style="padding: 8px 0;">${companyName || 'Confidential'}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af;">Received At</td><td style="padding: 8px 0;">${timestamp}</td></tr>
        </table>
        <div style="margin-top: 24px; padding: 12px 16px; background: rgba(99,102,241,0.1); border-radius: 8px; font-size: 12px; color: #9ca3af;">
          <strong>🔒 Anonymity Guarantee:</strong> This report was submitted through the Havilah Anonymous Vault. No IP addresses, user IDs, or identifying metadata have been stored. The submitter's identity is structurally unrecoverable.
        </div>
      </div>
      <div style="padding: 16px 32px; background: rgba(255,255,255,0.03); font-size: 11px; color: #6b7280; text-align: center;">
        Clinical Hotline: ${CLINICAL_HOTLINE} &bull; Havilah Whistleblower Protection System
      </div>
    </div>
  `;

  return sendMail({
    to: recipient,
    subject: `🛡️ Anonymous Hazard Report ${reportId} - ${(urgency || 'standard').toUpperCase()} Priority`,
    html
  });
}

/**
 * Sends a welcome email containing HR credentials and activation codes to newly provisioned HR Admin.
 */
async function sendHrWelcomeEmail({ to, companyName, password, loginUrl, activationUrl, activationCodes }) {
  const codesListHtml = (activationCodes || []).map(c => `<li style="font-family: monospace; font-weight: bold; color: #10b981;">${c}</li>`).join('');

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; color: #f8fafc; border-radius: 16px; overflow: hidden; box-shadow: 0 20px 25px -5px rgba(0,0,0,0.3);">
      <div style="background: linear-gradient(135deg, #0d9488, #0284c7); padding: 28px 32px;">
        <h1 style="margin: 0; color: #ffffff; font-size: 22px;">🎉 Welcome to Havilah Platform</h1>
        <p style="margin: 6px 0 0; color: rgba(255,255,255,0.85); font-size: 14px;">ISO 45003 Workplace Compliance & Psychosocial Risk Platform</p>
      </div>
      <div style="padding: 28px 32px;">
        <p style="font-size: 15px; line-height: 1.6; color: #cbd5e1;">
          Hello HR Administrator,<br><br>
          A new tenant account has been provisioned for <strong>${companyName}</strong>. You can now log into your HR Compliance Portal to manage your organization's risk assessment cycles.
        </p>

        <!-- Login Credentials Card -->
        <div style="background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 20px; margin: 20px 0;">
          <h3 style="margin: 0 0 12px 0; color: #38bdf8; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px;">🔑 HR Admin Login Credentials</h3>
          <p style="margin: 4px 0; font-size: 14px;"><strong>Portal URL:</strong> <a href="${loginUrl || 'http://localhost:3000/login.html'}" style="color: #38bdf8; text-decoration: underline;">${loginUrl || 'http://localhost:3000/login.html'}</a></p>
          <p style="margin: 4px 0; font-size: 14px;"><strong>Email:</strong> <span style="font-family: monospace; font-weight: bold; color: #ffffff;">${to}</span></p>
          <p style="margin: 4px 0; font-size: 14px;"><strong>Password:</strong> <span style="font-family: monospace; font-weight: bold; color: #ffffff;">${password}</span></p>
        </div>

        <!-- Activation Codes Card -->
        ${activationCodes && activationCodes.length > 0 ? `
        <div style="background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 20px; margin: 20px 0;">
          <h3 style="margin: 0 0 12px 0; color: #34d399; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px;">🎫 Employee Activation Codes</h3>
          <p style="margin: 4px 0 12px 0; font-size: 13px; color: #94a3b8;">Share these codes with participating employees to register at <a href="${activationUrl || 'http://localhost:3000/register.html'}" style="color: #38bdf8;">${activationUrl || 'http://localhost:3000/register.html'}</a>:</p>
          <ul style="margin: 0; padding-left: 20px; line-height: 1.8;">
            ${codesListHtml}
          </ul>
        </div>
        ` : ''}

        <p style="font-size: 12px; color: #64748b; margin-top: 24px;">
          For security, please log in and change your password upon your first access.
        </p>
      </div>
    </div>
  `;

  return sendMail({
    to,
    subject: `🚀 Havilah Tenant Provisioned - HR Login Credentials for ${companyName}`,
    html
  });
}

module.exports = {
  sendMail,
  sendClinicalDispatch,
  sendInterventionAlert,
  sendWhistleblowerAlert,
  sendHrWelcomeEmail,
  CLINICAL_EMAIL,
  CLINICAL_HOTLINE,
  NOTIFICATION_RECIPIENT
};
